### ISSUE TITLE
Show labels, milestones and assignee in issue oneboxes.

### ISSUE THREAD

**Issue by Unihedro** [shu8/SEChat-githubOneboxer#1]
For example:

![](https://i.imgur.com/cBjrlfP.png)
![](https://i.imgur.com/AvZSwS0.png)

**Comment by shu8** [comment]
@Unihedro cheers - will look at this :)

**Comment by shu8** [comment]
Done :)

![](https://cloud.githubusercontent.com/assets/8850830/9292981/095cd996-440e-11e5-944d-1e5d0356d4e7.png)

Updated to version 1.1.

BTW the above assignments, milestones, etc.. are all for testing - I was looking at the different JSON responses! :)

**Comment by shu8** [comment]
@Unihedro (I forgot to ping you^^)

BTW - if I edit a ping into a message, would you receive the ping??

**Comment by Unihedro** [comment]
I get notifications even if you don't `@mention` me since I'm automatically watching the ticket by participating in it. And thanks!

**Comment by shu8** [comment]
oh - didn't know that! You can see I'm new to Github :P that's why I wanted you to submit an issue - so I can learn about it! :)

And you're welcome! :)
